// Emission of the generated `PublicSuffix.swift` source for `PublicSuffixGenerator`. Split out so the
// generator type body stays within the size/complexity gate; the emitted text is unchanged
// (DomainNormalizerParityTests pins the generator and emitted normalizers to the same behaviour).
extension PublicSuffixGenerator {
    /// Source text of the `String` domain helpers emitted into `PublicSuffix.swift`.
    ///
    /// The single source of truth for the EMITTED copy of `hasAllowedDomainScalars`
    /// and `isValidA_LABELDomain`; interpolated into `emit(...)`. The generator's
    /// own compiled copies (the `fileprivate` extension at the bottom of this file)
    /// mirror the same logic and are held in lockstep by `DomainNormalizerParityTests`,
    /// which runs `normalizedDomain` and the emitted `PublicSuffix` normalizer over
    /// shared fixtures.
    static let domainHelpersSource = """
        private extension String {
          var hasAllowedDomainScalars: Bool {
            unicodeScalars.allSatisfy { scalar in
              if scalar.value < 0x80 {
                return (65...90).contains(scalar.value)
                  || (97...122).contains(scalar.value)
                  || (48...57).contains(scalar.value)
                  || scalar.value == 45
                  || scalar.value == 46
              }
              switch scalar.properties.generalCategory {
              case .lowercaseLetter, .uppercaseLetter, .titlecaseLetter, .modifierLetter,
                .otherLetter, .decimalNumber, .letterNumber, .nonspacingMark, .spacingMark:
                return true
              default:
                return false
              }
            }
          }

          var isValidA_LABELDomain: Bool {
            guard allSatisfy({ character in
              character.isASCII && (character.isLetter || character.isNumber || character == "-" || character == ".")
            }) else {
              return false
            }
            return split(separator: ".", omittingEmptySubsequences: false)
              .allSatisfy { label in
                label.isEmpty == false
                  && label.first != "-"
                  && label.last != "-"
              }
          }
        }
        """

    /// Emits the final Swift source.
    public static func emit(iana: IANACatalogue, psl: PSLCatalogue) -> String {
        var out = ""
        out.reserveCapacity(1 << 18)

        out += """
            // =====================================================================
            // PublicSuffix — generated by PublicSuffixGeneratorPlugin — DO NOT EDIT.
            //
            // Sources:
            //   IANA Root Zone Database  — \(iana.version)
            //   Mozilla PSL (ICANN only) — \(psl.version)
            //                              \(psl.commit)
            //
            // Counts:
            //   IANA single-label TLDs    = \(iana.tlds.count)
            //   PSL ICANN literal suffixes = \(psl.suffixes.count)
            //   PSL ICANN wildcard rules   = \(psl.wildcardParents.count)
            //   PSL ICANN exceptions       = \(psl.exceptions.count)
            // =====================================================================

            import Foundation

            extension TopLevelDomain {

            """

        for tld in iana.tlds {
            let identifier = swiftIdentifier(for: tld)
            out +=
                "  public static let \(identifier) = TopLevelDomain(\"\(swiftStringLiteral(tld))\")\n"
        }

        out += """
            }

            /// Public-suffix catalog sourced from IANA + the ICANN section of the
            /// Mozilla Public Suffix List. The catalog is purely informational: the
            /// DSL never auto-rejects an unknown suffix. Callers who want strict
            /// rejection MUST consult `PublicSuffix.contains(_:)` themselves.
            public enum PublicSuffix {

              /// IANA Root Zone single-label TLDs.
              public static let icannTLDs: Set<String> = [

            """

        for tld in iana.tlds {
            out += "    \"\(swiftStringLiteral(tld))\",\n"
        }

        out += """
              ]

              /// Literal ICANN section rules from the Mozilla Public Suffix List.
              public static let icannSuffixes: Set<String> = [

            """

        for suffix in psl.suffixes {
            out += "    \"\(swiftStringLiteral(suffix))\",\n"
        }

        out += """
              ]

              /// Wildcard-rule parents from the ICANN section of the Mozilla
              /// Public Suffix List. A parent here means every direct child is
              /// a public suffix, while the parent itself is not.
              public static let icannWildcardParents: Set<String> = [

            """

        for suffix in psl.wildcardParents {
            out += "    \"\(swiftStringLiteral(suffix))\",\n"
        }

        out += """
              ]

              /// Exception rules from the ICANN section of the Mozilla Public
              /// Suffix List. These entries are explicitly not public suffixes;
              /// their parent suffix is the prevailing rule.
              public static let icannExceptions: Set<String> = [

            """

        for suffix in psl.exceptions {
            out += "    \"\(swiftStringLiteral(suffix))\",\n"
        }

        appendQueryAPI(into: &out)
        return out
    }

    /// Appends the static `PublicSuffix` query API (contains / longestMatch / normalizedDomain) and
    /// the single-sourced `String` domain helpers — the tail of the generated file.
    static func appendQueryAPI(into out: inout String) {
        out += """
              ]

              /// Returns true if `suffix` is a known public suffix.
              public static func contains(_ suffix: String) -> Bool {
                guard let normalized = normalizedDomain(suffix) else { return false }
                if icannExceptions.contains(normalized) { return false }
                if icannSuffixes.contains(normalized) { return true }

                let labels = normalized.split(separator: ".", omittingEmptySubsequences: false)
                guard labels.count > 1 else { return false }
                let parent = labels.dropFirst().joined(separator: ".")
                return icannWildcardParents.contains(parent)
              }

              /// Returns the longest public suffix that matches a trailing portion
              /// of `host` using the PSL matching algorithm's literal, wildcard,
              /// and exception rule precedence.
              public static func longestMatch(for host: String) -> String? {
                guard let normalized = normalizedDomain(host) else { return nil }
                let labels = normalized.split(separator: ".", omittingEmptySubsequences: false).map(String.init)

                for index in labels.indices {
                  let candidate = labels[index...].joined(separator: ".")
                  if icannExceptions.contains(candidate) {
                    let suffixLabels = labels[labels.index(after: index)...]
                    guard suffixLabels.isEmpty == false else { return nil }
                    return suffixLabels.joined(separator: ".")
                  }
                }

                var best: String?
                for index in labels.indices {
                  let candidate = labels[index...].joined(separator: ".")
                  if icannSuffixes.contains(candidate), isLonger(candidate, than: best) {
                    best = candidate
                  }
                  let nextIndex = labels.index(after: index)
                  if nextIndex < labels.endIndex {
                    let wildcardParent = labels[nextIndex...].joined(separator: ".")
                    if icannWildcardParents.contains(wildcardParent), isLonger(candidate, than: best) {
                      best = candidate
                    }
                  }
                }
                return best
              }

              private static func isLonger(_ candidate: String, than current: String?) -> Bool {
                guard let current else { return true }
                return candidate.split(separator: ".").count > current.split(separator: ".").count
              }

              // Internal (not private) so DomainNormalizerParityTests can run it
              // directly against the generator-side `PublicSuffixGenerator.normalizedDomain`.
              static func normalizedDomain(_ value: String) -> String? {
                let lowercased = value.lowercased()
                guard lowercased.isEmpty == false, lowercased.hasAllowedDomainScalars else {
                  return nil
                }
                // Lenient `URL(string:)` deliberately runs Foundation's IDNA
                // (U-label -> A-label); `isValidA_LABELDomain` re-checks ASCII LDH.
                guard
                  let url = URL(string: "https://\\(lowercased)"),
                  let host = url.host(percentEncoded: false)?.lowercased(),
                  host.isValidA_LABELDomain
                else {
                  return nil
                }
                return host
              }
            }

            \(domainHelpersSource)

            """
    }
}
